###               ____                    _
#  ____ _____  __/ ___\_   _  __ _ _ ____| |
# / __// _ \ \/ / /  _| | | |/ _' | '_/ _' |
# \__ \  __/>  <\ \_| | |_| | (_) | || (_) |
# /___/\___/_/\_\\____/\___/ \__,_|_| \__,_|
#
#   PROTECTS YOUR ANUS SINCE: 27 Dec. 2016
###
name: SexGuard
main: sex\guard\Manager
version: 1.2.0
api: 4.0.0

author: sex_KAMAZ
website: https://vk.com/infernopage

load: POSTWORLD

commands:
  rg:
    description: 'Показывает помощь или список команд управления регионами'
    permission: 'sexguard.command.rg'

permissions:
  sexguard.command.rg:
    default: true
  sexguard.noflag:
    description: 'Игнорирование флагов внутри регионов'
    default: op
  sexguard.all:
    description: 'Доступ ко всем функциям sexGuard'
    default: op